// This file is auto-generated by script
// DO NOT EDIT THIS FILE DIRECTLY

export const assetsData = {
  "beds": [],
  "catalogue": [
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/1.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/10.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/11.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/12.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/13.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/14.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/15.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/16.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/17.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/18.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/19.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/2.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/20.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/21.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/22.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/23.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/24.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/25.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/26.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/27.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/28.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/29.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/3.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/30.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/31.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/32.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/33.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/34.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/35.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/36.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/37.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/38.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/39.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/4.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/40.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/41.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/42.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/43.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/44.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/45.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/46.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/47.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/48.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/49.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/5.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/50.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/51.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/52.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/53.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/54.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/55.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/56.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/57.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/58.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/59.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/6.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/60.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/61.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/7.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/8.png?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/catalogue/9.png?raw=true",
      "caption": ""
    }
  ],
  "cupboards": [
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.19_2042f2ca.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.20_1ae083fe.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.20_d6ccd792.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.21_3d1622f4.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.21_8d3603b8.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.22_0222e312.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.22_1140e03c.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.23_767cd37f.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.24_72f720d2.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.25_2f6636b6.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.25_ab940a78.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fbaby_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.26_fc0b475e.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.38_87f91f1f.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.39_8df61a09.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.39_e7ce01f4.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.40_66e0c565.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.40_83ff6c4b.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.40_d844ba3e.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.41_45a83cf8.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.41_b7a25e7a.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.42_9f15abf2.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.42_a35aa222.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.42_b51616d7.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.43_cbf8eb65.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.43_f787c501.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.44_399430b5.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.44_54e5d694.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.44_fb0aadd9.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.45_13349e6c.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.45_23914712.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.45_ad9d72a7.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsamples/WhatsApp%20Image%202025-07-04%20at%2023.57.46_bf8ebefd.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsteel_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.41_81f4817f.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsteel_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.41_860f6a01.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsteel_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.41_b13ed838.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsteel_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.42_17ce847b.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsteel_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.42_e92cf3d2.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/cupboards%2Fsteel_cupboards/WhatsApp%20Image%202025-07-05%20at%2002.57.43_7e9ff2bd.jpg?raw=true",
      "caption": ""
    }
  ],
  "mattresses": [],
  "others": [
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/others%2FironBoards/WhatsApp%20Image%202025-07-05%20at%2002.57.31_a1854d6a.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/others%2FironBoards/WhatsApp%20Image%202025-07-05%20at%2002.57.32_c5f4c56a.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/others%2FironBoards/WhatsApp%20Image%202025-07-05%20at%2002.57.39_5decaeb8.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/others%2FironBoards/WhatsApp%20Image%202025-07-05%20at%2002.57.39_937eff6a.jpg?raw=true",
      "caption": ""
    }
  ],
  "racksNshelves": [
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FbookRacks/WhatsApp%20Image%202025-07-05%20at%2002.57.14_0b7ffedb.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FbookRacks/WhatsApp%20Image%202025-07-05%20at%2002.57.14_a5b0d868.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FbookRacks/WhatsApp%20Image%202025-07-05%20at%2002.57.15_77ea1261.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FbookRacks/WhatsApp%20Image%202025-07-05%20at%2002.57.16_7ff7235f.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FbookRacks/WhatsApp%20Image%202025-07-05%20at%2002.57.16_b68f88cf.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FbookRacks/WhatsApp%20Image%202025-07-05%20at%2002.57.17_97133ed6.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FchestDrawers/WhatsApp%20Image%202025-07-05%20at%2002.57.22_0565ff26.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FchestDrawers/WhatsApp%20Image%202025-07-05%20at%2002.57.26_b9ec20b3.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FchestDrawers/WhatsApp%20Image%202025-07-05%20at%2002.57.27_345ee287.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FchestDrawers/WhatsApp%20Image%202025-07-05%20at%2002.57.27_d8a19fba.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/racksNshelves%2FchestDrawers/WhatsApp%20Image%202025-07-05%20at%2002.57.28_d7b91923.jpg?raw=true",
      "caption": ""
    }
  ],
  "tables": [
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.28_806dbe90.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.29_3643f781.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.29_4c5c2f45.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.29_efdb2dde.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.30_0f1369d9.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.30_69dbadfa.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.30_a23dce4b.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.30_b91cc33e.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.31_8021fd6d.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.31_c6602ecc.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.33_357707c9.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.33_47a5ed6a.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.36_bc5a2291.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.36_e7dce4b7.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.36_f746c8a4.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.37_1763e534.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.37_39fe269c.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.38_2b8f74d3.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.38_6ba91597.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.38_fe6ec23b.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.43_d6cbb10c.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.43_f5a7dab7.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.44_1a401090.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.44_2037f367.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.44_5b8e2b85.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.45_8c66b16d.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.45_c6fff9a2.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.45_ddcc5e58.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.46_0b21d8f3.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.46_93a99b04.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.46_992f3c77.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FdressingTables/WhatsApp%20Image%202025-07-05%20at%2002.57.47_654f70d9.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/01wtbs001.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/02wtbs002.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/03wtb003.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/04wtbl001.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/05wtbl002.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/06wtbl004.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/07wtbl005.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/08wt.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb001.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb002.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb003.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb004.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb005.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb006.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb007.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/ctb010.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/wtr001.jpg?raw=true",
      "caption": ""
    },
    {
      "url": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/tables%2FwritingTables/wtr002.jpg?raw=true",
      "caption": ""
    }
  ]
} as const;
