// This file is auto-generated by script
// DO NOT EDIT THIS FILE DIRECTLY

export const assetsData = {
  "cat": [],
  "w2": [
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2d/WhatsApp%20Image%202025-07-02%20at%2020.09.06_73e1d7b3.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2d/WhatsApp%20Image%202025-07-02%20at%2020.09.13_0532e7c1.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2d/WhatsApp%20Image%202025-07-02%20at%2020.09.16_e6ac4313.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.08.54_b2db4ca7.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.08.59_c4e5633a.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.04_e868c45a.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.08_659915f3.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.09_3a2668b8.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.09_d059021a.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.10_db2f2bce.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.11_0f86fd77.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.11_1dca3c0a.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.12_872c1223.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.13_ecf620bf.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2hc/WhatsApp%20Image%202025-07-02%20at%2020.09.16_74738ec1.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2l/WhatsApp%20Image%202025-07-02%20at%2020.09.08_42a7c6dd.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2l/WhatsApp%20Image%202025-07-02%20at%2020.09.14_709239df.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w2%2Fw2l/WhatsApp%20Image%202025-07-02%20at%2020.09.17_c250c180.jpg?raw=true",
      "caption": ""
    }
  ],
  "w3": [
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.10.55_71fcca66.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.10.57_61753d52.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.10.58_07b1b83c.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.10.58_f295ba9a.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.10.59_19897e7d.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.11.00_b85e0b7d.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.11.06_2ab45163.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3ld/WhatsApp%20Image%202025-07-02%20at%2020.15.31_4726832c.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3n/WhatsApp%20Image%202025-07-02%20at%2020.15.32_201cb8e2.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3n/WhatsApp%20Image%202025-07-02%20at%2020.15.32_c73c5c0b.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3n/WhatsApp%20Image%202025-07-02%20at%2020.15.34_2de5b4a3.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.10.56_41f5b367.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.10.57_5c814b6a.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.10.59_1f8bf3af.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.11.00_6f3bbe98.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.11.02_191de520.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.11.03_bc5c7943.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.11.04_597f8a70.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.11.05_89f22804.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.15.33_8b50374d.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.15.33_c833ba01.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w3%2Fw3sd/WhatsApp%20Image%202025-07-02%20at%2020.15.34_4ac86e90.jpg?raw=true",
      "caption": ""
    }
  ],
  "w4": [
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.09.18_c0f7b284.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.09.19_cb744aa7.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.09.20_64bced98.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.10.50_f9f74e6c.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.10.51_b5e20d3b.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.10.51_f15c5291.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.10.52_99d234e4.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.10.53_024c1dee.jpg?raw=true",
      "caption": ""
    },
    {
      "image": "https://github.com/mal-sizu/wa_funri_bot/blob/master/assets/w4/WhatsApp%20Image%202025-07-02%20at%2020.10.53_26ebcf84.jpg?raw=true",
      "caption": ""
    }
  ]
} as const;
