import { promises as fs } from 'fs';
import path from 'path';
import { getImageUrls, getSubdirectories } from './util_fetchers';

const ASSETS_ROOT = path.join(__dirname, '..', '..', 'assets');

async function generateAssetsData() {
  const assetsData: Record<string, Array<{ image: string; caption: string }>> = {};
  
  try {
    const topLevelFolders = (await getSubdirectories(ASSETS_ROOT))
      .map(fullPath => path.basename(fullPath));

    for (const folder of topLevelFolders) {
      const { urls } = await getImageUrls(folder, { recursive: true });
      assetsData[folder] = urls.map(imageUrl => ({ image: imageUrl, caption: '' }));
    }

    const output = `// This file is auto-generated by script
// DO NOT EDIT THIS FILE DIRECTLY

export const assetsData = ${JSON.stringify(assetsData, null, 2)} as const;
`;

    await fs.writeFile(path.join(__dirname, 'assets_data.ts'), output);
    console.log('assets_data.ts generated successfully');
  } catch (error) {
    console.error('Error generating assets data:', error);
    process.exit(1);
  }
}

generateAssetsData();